
version: '3.8'
services:
  php-apache-environment:
    build: 
      context: ./php
    depends_on:
      - db
    ports:
      - 8000:80
    networks: 
      - bridge

  db:

    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TEST
      MYSQL_USER: root
      MYSL_PASSWORD: root
    ports:
      - "9906:3306"
    networks: 
      - bridge

  phpmyadmin:

    image: phpmyadmin/phpmyadmin
    ports:
      - '8082:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
    networks: 
      - bridge

networks:
  bridge:
